//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlicaan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string IDUser { get; set; }
        public string URole { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
