//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlicaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuatAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuatAn()
        {
            this.ChiTietSuatAns = new HashSet<ChiTietSuatAn>();
        }
    
        public int ID { get; set; }
        public string IDUser { get; set; }
        public System.DateTime Thoigiandat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSuatAn> ChiTietSuatAns { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
